apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: default
type: kubernetes.io/lb-csi
data:
  jwt: |-
    ZXlKaGJHY2lPaUpTVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnJhV1FpT2lKaE9tTnlaV1F0
    WVNJc0luSnZiR1VpT2lKaE9tMWhibUZuWlhJaUxDSmhkV1FpT2lKTWFXZG9kRTlUSWl3aVpYaHdJ
    am94TmpBM01UVXlPVE0yTENKcWRHa2lPaUpoT0dVeE9UZzBNeTA0WkRrM0xUUmhaVEF0WW1NMU1D
    MDRNamhpTVdZNU5qYzNNamtpTENKcFlYUWlPakUyTURRMU5qQTVNellzSW1semN5STZJbU4xYzNS
    dmJXVnlMV0VpTENKdVltWWlPakUyTURRMU5qQTVNellzSW5OMVlpSTZJa3hwWjJoMFQxTWlmUS5a
    d1EwbWV1SEszYnZ3M2ZhUkhaZ2g0WHNkc2U5NVZTSy1ub1BfbEIzeUotSmI4Qno3Wk1IbHhVRXBR
    RUNRZkVaYW4tcUNaM1lISlR2VmI4NEZwTEFrU0hkd3Q3X0RlNUQ4R281SkFOdy02b01MOGF0Wkty
    MHQ2TTZxMTZhWWVfVzBOMERRTElFcWJLWnFDSS15enhpZnF4LU5XZm5pYTZIRWRNVjZ0Vm42WUxf
    OHpPUFUyTjh5dDFNMllrWEJka1FyeUVDV2N5ZjJaeXllRGhSQm1RTno5UndKdXc5RDNLdDROR0pq
    NXBlNXlQU3dfLW9yRjNTaVh5WFJqMjgzYUZ3MVZYYjZDc2ZzWlVUTmptQXRqb3pWeHNjTFMyQk1S
    OVJ5UjFJMGpUQXoweWFTdGR6TjFPMTZkQ0dta2FlbzV6dHREQkJNSVhUTUVuSk9qUnE0QldpVFF=
