apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-mt-pvc
spec:
  storageClassName: example-mt-sc
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
