---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: lb-csi-ctrl-sa
spec:
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - secret
  - emptyDir

---

apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: lb-csi-node-sa
spec:
  allowedCapabilities:
  - SYS_ADMIN
  allowedHostPaths:
  - pathPrefix: /var/lib/kubelet
  - pathPrefix: /dev
  - pathPrefix: /lib/modules
  - pathPrefix: /var/lib/kubelet/plugins_registry/
  - pathPrefix: /var/lib/kubelet/plugins/csi.lightbitslabs.com
  fsGroup:
    rule: RunAsAny
  hostNetwork: true
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - secret
  - hostPath
  - emptyDir

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lb-csi-node
rules:
  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs: ['use']
    resourceNames:
    - lb-csi-node-sa

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lb-csi-node
subjects:
  - kind: ServiceAccount
    name: lb-csi-node-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: lb-csi-node
  apiGroup: rbac.authorization.k8s.io
