# permissions for end users to view lightbits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lightbits-viewer-role
rules:
- apiGroups:
  - storage.metal-stack.io
  resources:
  - lightbits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.metal-stack.io
  resources:
  - lightbits/status
  verbs:
  - get
