
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - storage.metal-stack.io
  resources:
  - lightbits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.metal-stack.io
  resources:
  - lightbits/status
  verbs:
  - get
  - patch
  - update
